#ifndef WORKSPACE_H
#define WORKSPACE_H

/*
 * This file was autogenerated by OSQP-Python on July 05, 2022 at 17:36:25.
 * 
 * This file contains the prototypes for all the workspace variables needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#include "types.h"
#include "qdldl_interface.h"

// Data structure prototypes
extern csc Pdata;
extern csc Adata;
extern c_float qdata[2];
extern c_float ldata[28];
extern c_float udata[28];
extern OSQPData data;

// Settings structure prototype
extern OSQPSettings settings;

// Scaling structure prototypes
extern c_float Dscaling[2];
extern c_float Dinvscaling[2];
extern c_float Escaling[28];
extern c_float Einvscaling[28];
extern OSQPScaling scaling;

// Prototypes for linsys_solver structure
extern csc linsys_solver_L;
extern c_float linsys_solver_Dinv[30];
extern c_int linsys_solver_P[30];
extern c_float linsys_solver_bp[30];
extern c_float linsys_solver_sol[30];
extern c_float linsys_solver_rho_inv_vec[28];
extern qdldl_solver linsys_solver;

// Prototypes for solution
extern c_float xsolution[2];
extern c_float ysolution[28];

extern OSQPSolution solution;

// Prototype for info structure
extern OSQPInfo info;

// Prototypes for the workspace
extern c_float work_rho_vec[28];
extern c_float work_rho_inv_vec[28];
extern c_float work_x[2];
extern c_float work_y[28];
extern c_float work_z[28];
extern c_float work_xz_tilde[30];
extern c_float work_x_prev[2];
extern c_float work_z_prev[28];
extern c_float work_Ax[28];
extern c_float work_Px[2];
extern c_float work_Aty[2];
extern c_float work_delta_y[28];
extern c_float work_Atdelta_y[2];
extern c_float work_delta_x[2];
extern c_float work_Pdelta_x[2];
extern c_float work_Adelta_x[28];
extern c_float work_D_temp[2];
extern c_float work_D_temp_A[2];
extern c_float work_E_temp[28];

extern OSQPWorkspace workspace;

#endif // ifndef WORKSPACE_H
